version: '3.8'
services:
  database:
    image: postgres:13-alpine
    init: true
    environment:
      - POSTGRES_DB=short_url
      - POSTGRES_USER=short_url
      - POSTGRES_PASSWORD=short_url
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      - ./docker/data:/tmp/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

volumes:
  db_data: